### ISSUE TITLE
how can i ack broken messages

### ISSUE THREAD

**Issue by neilrogers** [hunterloftis/jackrabbit#28] opened 2016-01-15 01:48 UTC
Hi I have a worker that is synchronous i.e processes 1 message at a time. Sometimes messages are inserted corrupted or appear to be corrupted and amqp throws an error. How can i catch these errors then ack the message. So i can move on to the next message. At the moment the thrown error kills my node process and forever restarts it and try to process the corrupted message again.

```
events.js:85
throw er; // Unhandled 'error' event

Error: Channel closed by server: 406 (PRECONDITION-FAILED) with message "PRECONDITION_FAILED - unknown delivery tag 3"
at Channel.C.accept (/opt/jetmobile/testing/JetMobPoller/node_modules/jackrabbit/node_modules/amqplib/lib/channel.js:406:17)
at Connection.mainAccept [as accept] (/opt/jetmobile/testing/JetMobPoller/node_modules/jackrabbit/node_modules/amqplib/lib/connection.js:63:33)
at Socket.go (/opt/jetmobile/testing/JetMobPoller/node_modules/jackrabbit/node_modules/amqplib/lib/connection.js:474:48)
at Socket.emit (events.js:104:17)
at emitReadable_ (_stream_readable.js:424:10)
at emitReadable (_stream_readable.js:418:7)
at readableAddChunk (_stream_readable.js:174:11)
at Socket.Readable.push (_stream_readable.js:126:10)
at TCP.onread (net.js:538:20)
error: Forever detected script exited with code: 1
```

my code looks like this, If i use noAck: true then the process is not synchronous

```
rabbitmq
    .default()
    .queue({ name: queue, durable: false, messageTtl: undefined })
    .consume(onRun,{ noAck: false });

function onRun(data, ack) {
    //do stuff
    //after stuff is done
    ack();
}
```

**Comment by hunterloftis** [comment] 2016-01-19 20:38
Hi, can you write a test so I can reproduce the issue?

**Comment by neilrogers** [comment] 2016-01-21 02:42
thats the thing I can't figure out how these broken messages are being added. All i know is I see this error every now and then "Channel closed by server: 406 (PRECONDITION-FAILED) with message  - unknown delivery tag 3"

I have not see this error in a little while. Maybe I'll keep an eye on it and try and fix it myself and share my findings. feel free to close the bug. thanks

**Comment by redflasher** [comment] 2016-07-28 15:02
error is appears when send "ack" two or more times for one message in queue.

**Comment by jpepper07** [comment] 2016-10-19 17:59
I get this regularly through out the day on an app that handles under 1000 messages a day. I am only acking in one location.

`function onMessage(data, ack, nack){
    console.log('received msg');
    switchboard(data,function(err, result){
        if(err){
            console.log(err);
            //should publish to failure queue
            publishToFailure(data);
            ack();
        }else{
            ack();
        }
        console.log(result);
    });
}`

**Comment by matmar10** [comment] 2018-06-22 08:55
Closing this since it's an old question. @neilrogers please reopen if you would like to request further help or investigation.

**Closed by matmar10** 2018-06-22 08:55 UTC
Labels: question

**Comment by DanielMarquesz** [comment] 2022-01-14 17:50
I have the same issue recently, then i close the channel after to ack the message.
